name: 'Star Wars quote action'
description: 'Dummy action returning Star Wars quotes'
author: 'Dominik Maszczyk'
branding:
  icon: 'message-square'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
