name: Test

on:
  push: {}
  schedule:
    - cron: '0 0 1 * *'

jobs:
  success:
    name: Runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Might the force be with you
        uses: ./
